version: "3.8"

x-web-template: &web-template
  build: .
  expose:
    - "3000"
  environment:
    DATABASE_URL: "postgres://local_user:local_password@postgres/rinha-backend-2024-q1"
  depends_on:
    postgres:
      condition: service_healthy
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: "180MB"

services:
  web1:
    <<: *web-template
    hostname: web1

  web2:
    <<: *web-template
    hostname: web2

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rinha-backend-2024-q1
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_password
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U local_user -d rinha-backend-2024-q1'",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "40MB"
